const gamesData = [
  {
    name: 'CATAN',
    thumbnail: 'https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__thumb/img/8a9HeqFydO7Uun_le9bXWPnidcA=/fit-in/200x150/filters:strip_icc()/pic2419375.jpg',
    image: 'https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__original/img/xV7oisd3RQ8R-k18cdWAYthHXsA=/0x0/filters:format(jpeg)/pic2419375.jpg',
    description: "In CATAN (formerly The Settlers of Catan), players try to be the dominant force on the island of Catan by building settlements, cities and roads. On each turn dice are rolled to determine which resources the island produces. Players build structures by 'spending' resources (sheep, wheat, wood, brick and ore) which are represented by the relevant resource cards; each land type, with the exception of the unproductive desert, produces a specific resource: hills produce brick, forests produce wood, mountains produce ore, fields produce wheat, and pastures produce sheep.&#10;&#10;Set-up includes randomly placing large hexagonal tiles (each depicting one of the five resource-producing terrain types--or the desert) in a honeycomb shape and surrounding them with water tiles, some of which contain ports of exchange. A number disk, the value of which will correspond to the roll of two 6-sided dice, are placed on each terrain tile. Each player is given two settlements (think: houses) and roads (sticks) which are placed on intersections and borders of the terrain tiles. Players collect a hand of resource cards based on which terrain tiles their last-placed settlement is adjacent to. A robber pawn is placed on the desert tile.&#10;&#10;A turn consists of rolling the dice, collecting resource cards based on this dice roll and the position of settlements (or upgraded cities&mdash;think: hotels), turning in resource cards (if possible and desired) for improvements, trading cards at a port, possibly playing a development card, or trading resource cards with other players. If the dice roll is a 7, the active player moves the robber to a new terrain tile and steals a resource card from another player who has a settlement adjacent to that tile.&#10;&#10;Points are accumulated by building settlements and cities, having the longest road or the largest army (from some of the development cards), and gathering certain development cards that simply award victory points. When a player has gathered 10 points (some of which may be held in secret), s/he announces this and claims the win.&#10;&#10;",
    yearPublished: 1995,
    minPlayers: 3,
    maxPlayers: 4,
    playTime: 120,
    minAge: 10,
  },
  {
    name: 'Dice Throne',
    thumbnail: 'https://cf.geekdo-images.com/fx_i2HMyAeCyAh94fH7a1Q__thumb/img/qJVeKAWpB7REM6lraF1sDQy4Ciw=/fit-in/200x150/filters:strip_icc()/pic4490309.png',
    image: 'https://cf.geekdo-images.com/fx_i2HMyAeCyAh94fH7a1Q__original/img/h2oJ0Z27OoUEHE5LgR_xoRoHfIE=/0x0/filters:format(png)/pic4490309.png',
    description: "&#10;&#10;&#10;    &#10;        GAME SYSTEM&#10;&#10;    &#10;    &#10;         This entry is to allow for discussion/rating of the game system as a whole. It is not for a specific product or release. Versions will appear on the individual item pages.&#10;&#10;    &#10;&#10;&#10;&#10; Dice Throne is a fast-paced 2-6 player combat game, whether 1v1, 2v2, 3v3, 2v2v2, or free-for-all. Select from a variety of heroes that play and feel completely distinct from one another. Attack opponents and activate abilities by rolling your hero's unique set of five dice. Accumulate combat points and spend them on cards that have a large range of effects, such as granting permanent hero upgrades, applying status effects, and manipulating dice directly whether yours, your teammate's, or even your opponent's.&#10;&#10;Each player needs their own hero dice and cards to play Dice Throne. &quot;Season One&quot; of the game was released in a single box that contains components for six heroes, while &quot;Season Two&quot; was released in four small sets that each contain components for two heroes as well as a &quot;Battle Chest&quot; that has these four small sets. Heroes can be mixed-and-matched across seasons.&#10;&#10;Linked entries in the BGG database:&#10;&#10;&#10;    Dice Throne: Season One&#10;    Dice Throne: Season One ReRolled&#10;    Dice Throne: Season One ReRolled &#226;&#128;&#147; Barbarian v. Moon Elf&#10;    Dice Throne: Season One ReRolled &#226;&#128;&#147; Monk v. Paladin&#10;    Dice Throne: Season One ReRolled &#226;&#128;&#147; Pyromancer v. Shadow Thief&#10;    Dice Throne: Season One ReRolled &#226;&#128;&#147; Treant v. Ninja&#10;    Dice Throne: Season Two &#226;&#128;&#147; Battle Chest&#10;    Dice Throne: Season Two &#226;&#128;&#147; Seraph v. Vampire Lord&#10;    Dice Throne: Season Two &#226;&#128;&#147; Tactician v. Huntress&#10;    Dice Throne: Season Two &#226;&#128;&#147; Gunslinger v. Samurai&#10;    Dice Throne: Season Two &#226;&#128;&#147; Cursed Pirate v. Artificer&#10;    Dice Throne Adventures&#10;&#10;&#10;",
    yearPublished: 2018,
    minPlayers: 2,
    maxPlayers: 6,
    playTime: 40,
    minAge: 8,
  },
  {
    name: 'Monopoly',
    thumbnail: 'https://cf.geekdo-images.com/9nGoBZ0MRbi6rdH47sj2Qg__thumb/img/ezXcyEsHhS9iRxmuGe8SmiLLXlM=/fit-in/200x150/filters:strip_icc()/pic5786795.jpg',
    image: 'https://cf.geekdo-images.com/9nGoBZ0MRbi6rdH47sj2Qg__original/img/bA8irydTCNlE38QSzM9EhcUIuNU=/0x0/filters:format(jpeg)/pic5786795.jpg',
    description: "Theme&#10;Players take the part of land owners, attempting to buy and then develop their land. Income is gained by other players visiting their properties and money is spent when they visit properties belonging to other players. When times get tough, players may have to mortgage their properties to raise cash for fines, taxes and other misfortunes.&#10;&#10;Gameplay&#10;On his turn, a player rolls two dice and moves that number of spaces around the board. If the player lands on an as-yet-unowned property, he has the opportunity to buy it and add it to his portfolio or allow the bank to auction it to the highest bidder. If a player owns all the spaces within a color group, he may then build houses and hotels on these spaces, generating even more income from opponents who land there. If he lands on a property owned by another player, he must pay that player rent according to the value of the land and any buildings on it. There are other places on the board which can not be bought, but instead require the player to draw a card and perform the action on the card, pay taxes, collect income, or even go to jail.&#10;&#10;Goal&#10;The goal of the game is to be the last player remaining with any money.&#10;&#10;Cultural impact on rules&#10;Monopoly is unusual in that the game has official, printed rules, but most players learn how to play from others, never actually learning the correct way to play. This has led to the canonization of a number of house rules that make the game more palatable to children (and sore losers) but harm the gameplay by preventing players from going bankrupt or slowing down the rate of property acquisition. One common house rule has players put any money paid to the bank in the center of the board, which jackpot a player may earn by landing on Free Parking. This prevents the game from removing money from play, and since players collect $200 each time they pass Go, this results in ever-increasing bankrolls and players surviving rents that should have bankrupted them. Another house rule allows players to take &quot;loans&quot; from the bank instead of going bankrupt, which means the game will never end. Some house rules arise out of ignorance rather than attempts to improve the game. For instance, many players don't know that properties landed on but left unbought go up for auction, and even some that know to auction don't know that the bidding starts at $1, meaning a player may pay well below the listed price for an auctioned property.&#10;&#10;",
    yearPublished: 1935,
    minPlayers: 2,
    maxPlayers: 8,
    playTime: 180,
    minAge: 8,
  },
  {
    name: 'Blokus',
    thumbnail: 'https://cf.geekdo-images.com/96YA5wUJDxtPkmPxemr5Qg__thumb/img/EBt2y7Awj5djyo185R7g6FV3P9g=/fit-in/200x150/filters:strip_icc()/pic2197702.jpg',
    image: 'https://cf.geekdo-images.com/96YA5wUJDxtPkmPxemr5Qg__original/img/sdX6o0TZpXjsDMw071k2P80wpYw=/0x0/filters:format(jpeg)/pic2197702.jpg',
    description: 'Blokus (officially pronounced &quot;Block us&quot;) is an abstract strategy game with transparent, Tetris-shaped, colored pieces that players are trying to play onto the board.  The only caveat to placing a piece is that it may not lie adjacent to your other pieces, but instead must be placed touching at least one corner of your pieces already on the board.&#10;&#10;There is a solitaire variation where one player tries to get rid of all the pieces in a single sitting.&#10;&#10;Goal of the Game:&#10;&#10;Each player has to fit as many of his/her 21 pieces on the board as possible.&#10;&#10;Components:&#10;Blokus Game Board (400 squares)&#10;84 game pieces (four 21-piece sets of red, green, blue, and yellow)&#10;Each color inlcudes:&#10;&#10;     1 one-square piece&#10;     1 piece with 2 squares&#10;     2 pieces with 3 squares&#10;     5 pieces with 4 squares&#10;     12 pieces with 5 squares&#10;&#10;&#10;',
    yearPublished: 2000,
    minPlayers: 2,
    maxPlayers: 4,
    playTime: 20,
    minAge: 7,
  },
  {
    name: 'Mansions of Madness',
    thumbnail: 'https://cf.geekdo-images.com/JtjGOgkaIxnLUeoV56cWFQ__thumb/img/eaj13E1FPWuVbXyBNBpewxXlVD0=/fit-in/200x150/filters:strip_icc()/pic814011.jpg',
    image: 'https://cf.geekdo-images.com/JtjGOgkaIxnLUeoV56cWFQ__original/img/47Cef6w56t2Vomn6bO8aT5p1ZiI=/0x0/filters:format(jpeg)/pic814011.jpg',
    description: 'Description from the publisher:&#10;&#10;Horrific monsters and spectral presences lurk in manors, crypts, schools, monasteries, and derelict buildings near Arkham, Massachusetts. Some spin dark conspiracies while others wait for hapless victims to devour or drive insane. It&rsquo;s up to a handful of brave investigators to explore these cursed places and uncover the truth about the living nightmares within.&#10;&#10;Designed by Corey Konieczka, Mansions of Madness is a macabre game of horror, insanity, and mystery for two to five players. Each game takes place within a pre-designed story that provides players with a unique map and several combinations of plot threads. These threads affect the monsters that investigators may encounter, the clues they need to find, and which climactic story ending they will ultimately experience. One player takes on the role of the keeper, controlling the monsters and other malicious powers within the story. The other players take on the roles of investigators, searching for answers while struggling to survive with their minds intact.&#10;&#10;Do you dare enter the Mansions of Madness?&#10;&#10;',
    yearPublished: 2011,
    minPlayers: 2,
    maxPlayers: 5,
    playTime: 180,
    minAge: 13,
  },
  {
    name: 'Potion Explosion',
    thumbnail: 'https://cf.geekdo-images.com/vwjYMFporFhvAU48k73MIw__thumb/img/uNBrY-gqZLq7aiv1E_pDsc3vmyE=/fit-in/200x150/filters:strip_icc()/pic7298696.jpg',
    image: 'https://cf.geekdo-images.com/vwjYMFporFhvAU48k73MIw__original/img/6sAfG89R42SJRv2wjiItRTMmcoQ=/0x0/filters:format(jpeg)/pic7298696.jpg',
    description: "Potion Explosion is a game for 2 to 4 players by Horrible Games.&#10;It was designed by Lorenzo Silva, Andrea Crespi and Stefano Castelli.&#10;&#10;Dear students, it's time for the final exams of the Potions class! The rules are always the same: Take an ingredient marble from the dispenser and watch the others fall. If you connect marbles of the same color, they explode and you can take them, too! Complete your potions using the marbles you collect, and drink them to unleash their magical power. Remember, though, that to win the Student of the Year award, being quick won't be enough: you'll also need to brew the most valuable potions in Potion Explosion!&#10;&#10;",
    yearPublished: 2015,
    minPlayers: 2,
    maxPlayers: 4,
    playTime: 45,
    minAge: 8,
  },
  {
    name: 'Everdell',
    thumbnail: 'https://cf.geekdo-images.com/fjE7V5LNq31yVEW_yuqI-Q__thumb/img/Cf_mYxR_VvdjTEPXseSurni2JNI=/fit-in/200x150/filters:strip_icc()/pic3918905.png',
    image: 'https://cf.geekdo-images.com/fjE7V5LNq31yVEW_yuqI-Q__original/img/HQ1ti16wT9lqja5_h3gUfHUIcVI=/0x0/filters:format(png)/pic3918905.png',
    description: "Within the charming valley of Everdell, beneath the boughs of towering trees, among meandering streams and mossy hollows, a civilization of forest critters is thriving and expanding. From Everfrost to Bellsong, many a year have come and gone, but the time has come for new territories to be settled and new cities established. You will be the leader of a group of critters intent on just such a task. There are buildings to construct, lively characters to meet, events to host&mdash;you have a busy year ahead of yourself. Will the sun shine brightest on your city before the winter moon rises?&#10;&#10;Everdell is a game of dynamic tableau building and worker placement.&#10;&#10;On their turn a player can take one of three actions:&#10;&#10;a) Place a Worker: Each player has a collection of Worker pieces. These are placed on the board locations, events, and on Destination cards. Workers perform various actions to further the development of a player's tableau: gathering resources, drawing cards, and taking other special actions.&#10;&#10;b) Play a Card: Each player is building and populating a city; a tableau of up to 15 Construction and Critter cards. There are five types of cards: Travelers, Production, Destination, Governance, and Prosperity. Cards generate resources (twigs, resin, pebbles, and berries), grant abilities, and ultimately score points. The interactions of the cards reveal numerous strategies and a near infinite variety of working cities.&#10;&#10;c) Prepare for the next Season: Workers are returned to the players supply and new workers are added. The game is played from Winter through to the onset of the following winter, at which point the player with the city with the most points wins.&#10;&#10;",
    yearPublished: 2018,
    minPlayers: 1,
    maxPlayers: 4,
    playTime: 80,
    minAge: 10,
  },
  {
    name: 'Super Mega Lucky Box',
    thumbnail: 'https://cf.geekdo-images.com/grnvMmEKa_jRg4ZBX5Fadw__thumb/img/Fs2vCJ0dkPZxMHm4A_vEkl0yiT0=/fit-in/200x150/filters:strip_icc()/pic6254861.png',
    image: 'https://cf.geekdo-images.com/grnvMmEKa_jRg4ZBX5Fadw__original/img/2jFwR_GdPUCUv6QjDxsgw3DQCkQ=/0x0/filters:format(png)/pic6254861.png',
    description: "Your goal in Super Mega Lucky Box is to score as many points as possible, and you'll do that mostly by crossing off the nine numbers printed in a 3x3 grid on the cards in front of you.&#10;&#10;During each of the four rounds, you shuffle 18 cards (numbered 1-9 twice), then reveal nine of those cards one by one. For each number revealed, you cross off a matching number on one of your cards, with you starting the game by choosing three out of five cards. Each time you complete a row or column, you receive the printed bonus next to it:&#10;&#10;&#10;     A lightning bolt, which you can spend to raise or lower the number that you're crossing off on a turn; spend three lightning bolts, for example, and you can change a 7 into either a 4 or a 1 (because the numbers &quot;wrap&quot;)&#10;     A moon, with the player who has the most moons scoring 6 points at game's end, while the player with the fewest loses 6 points (except in a two-player game)&#10;     A star, with you scoring 1, 4, or 9 points for collecting 1, 2, or 3 stars in a single round&#10;     A number, which you immediately cross off on one of your cards; if doing so completes another row or column, you score that bonus, too!&#10;     A question mark, which allows you to cross off any number.&#10;&#10;&#10;At the end of a round, you score points for each card that you've completely marked off, with the points diminishing each round from 15 in round one to 8 in round four. Each player then draws three new cards and keeps one of them.&#10;&#10;After four rounds, you score 1 point for each two spaces Xed on unfinished cards, then tally your points from completed cards, stars, and moons to see who has the highest score and wins.&#10;&#10;",
    yearPublished: 2021,
    minPlayers: 1,
    maxPlayers: 6,
    playTime: 20,
    minAge: 8,
  },
  {
    name: 'Dominion',
    thumbnail: 'https://cf.geekdo-images.com/j6iQpZ4XkemZP07HNCODBA__thumb/img/B2u2ghwlmI_qsUtCwuvcbnBcIqU=/fit-in/200x150/filters:strip_icc()/pic394356.jpg',
    image: 'https://cf.geekdo-images.com/j6iQpZ4XkemZP07HNCODBA__original/img/96COuakNiLRrjDLc1sM4Zxsw4WE=/0x0/filters:format(jpeg)/pic394356.jpg',
    description: "&quot;You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees. You want a Dominion! In all directions lie fiefs, freeholds, and feodums. All are small bits of land, controlled by petty lords and verging on anarchy. You will bring civilization to these people, uniting them under your banner.&#10;&#10;But wait! It must be something in the air; several other monarchs have had the exact same idea. You must race to get as much of the unclaimed land as possible, fending them off along the way. To do this you will hire minions, construct buildings, spruce up your castle, and fill the coffers of your treasury. Your parents wouldn't be proud, but your grandparents, on your mother's side, would be delighted.&quot;&#10;&#10;&mdash;description from the back of the box&#10;&#10;In Dominion, each player starts with an identical, very small deck of cards.  In the center of the table is a selection of other cards the players can &quot;buy&quot; as they can afford them.  Through their selection of cards to buy, and how they play their hands as they draw them, the players construct their deck on the fly, striving for the most efficient path to the precious victory points by game end.&#10;&#10;Dominion is not a Collectible Card Game (CCG), but the play of the game is similar to the construction and play of a CCG deck. The game comes with 500 cards. You select 10 of the 25 Kingdom card types to include in any given play&mdash;leading to immense variety.&#10;&#10;&mdash;user summary&#10;&#10;Part of the Dominion series.&#10;&#10;",
    yearPublished: 2008,
    minPlayers: 2,
    maxPlayers: 4,
    playTime: 30,
    minAge: 13,
  },
  {
    name: 'Above and Below',
    thumbnail: 'https://cf.geekdo-images.com/U0wpvRmBe65e4vwGf0Jbpg__thumb/img/jHLwKKWiJ-lHoaNIj0TrKAGm7QM=/fit-in/200x150/filters:strip_icc()/pic2398773.jpg',
    image: 'https://cf.geekdo-images.com/U0wpvRmBe65e4vwGf0Jbpg__original/img/gIlpowYQ7XzumYO0jZyVldxosBA=/0x0/filters:format(jpeg)/pic2398773.jpg',
    description: "Your last village was ransacked by barbarians. You barely had time to pick up the baby and your favorite fishing pole before they started the burning and pillaging. You wandered over a cruel desert, braved frozen peaks, and even paddled a log across a rough sea, kicking at the sharks whenever they got too close, the baby strapped tightly to your back.&#10;&#10;Then you found it! The perfect place to make your new home. But as soon as you had the first hut built, you discovered a vast network of caverns underground, brimming with shiny treasures, rare resources, and untold adventure. How could you limit your new village to the surface? You immediately start organizing expeditions and building houses underground as well as on the surface.&#10;&#10;With any luck, you'll build a village even stronger than your last-- strong enough, even, to turn away the barbarians the next time they come knocking.&#10;&#10;Above and Below is a mashup of town-building and storytelling where you and up to three friends compete to build the best village above and below ground. In the game, you send your villagers to perform jobs like exploring the cave, harvesting resources, and constructing houses. Each villager has unique skills and abilities, and you must decide how to best use them. You have your own personal village board, and you slide the villagers on this board to various areas to indicate that they've been given jobs to do. Will you send Hanna along on the expedition to the cave? Or should she instead spend her time teaching important skills to one of the young villagers?&#10;&#10;A great cavern lies below the surface, ready for you to explore-- this is where the storytelling comes in. When you send a group of villagers to explore the depths, one of your friends reads what happens to you from a book of paragraphs. You'll be given a choice of how to react, and a lot will depend on which villagers you brought on the expedition, and who you're willing to sacrifice to succeed. The book of paragraphs is packed with encounters of amazing adventure, randomly chosen each time you visit the cavern.&#10;&#10;At the end of the game, the player with the most well-developed village wins!&#10;&#10;The Kickstarter version of the game included the following items which are not found in the Retail version:&#10;&#10;     Villager Tool tokens&#10;     Lost Villagers&#10;     Swamp Villagers&#10;     Exclusive Stretch goals:&#10;     Creature Villagers&#10;     Quest Tokens&#10;     Underforest Tokens and PDF story book&#10;     Desert Labyrinth tokens and PDF story book &#10;     Wooden Goods&#10;&#10;&#10;This collection of items can be found in Above and Below: Expanded Edition Exclusives&#10;&#10;",
    yearPublished: 2015,
    minPlayers: 2,
    maxPlayers: 4,
    playTime: 90,
    minAge: 13,
  },
  {
    name: 'Near and Far',
    thumbnail: 'https://cf.geekdo-images.com/lm8OOgJupqd3Q-fZ3DsQhw__thumb/img/mZV5Pve42U5PlK-GkFSDTDXCzdg=/fit-in/200x150/filters:strip_icc()/pic3605785.jpg',
    image: 'https://cf.geekdo-images.com/lm8OOgJupqd3Q-fZ3DsQhw__original/img/hTV2P_-UPntaLbQB3Dl17LYz42A=/0x0/filters:format(jpeg)/pic3605785.jpg',
    description: "Four wanderers search for the Last Ruin, a city that legends say contains an artifact that will grant the greatest desires of the heart. A lost love, redemption, acceptance, a family rejoined-- these are the fires that fuel the wanderers' journeys, but can they overcome their own greed and inner demons on the way?&#10;&#10;In Near and Far, you and up to three friends explore many different maps in a search for the Last Ruin, recruiting adventurers, hunting for treasure, and competing to be the most storied traveler. You must collect food and equipment at town for long journeys to mysterious locales, making sure not to forget enough weapons to fight off bandits, living statues, and rusty robots! Sometimes in your travels you'll run into something unique and one of your friends will read what happens to you from a book of stories, giving you a choice of how to react, creating a new and memorable tale each time you play.&#10;&#10;Near and Far is a sequel to Above and Below and includes a book of encounters. This time players read over ten game sessions to reach the end of the story. Each chapter is played on a completely new map with unique art and adventures.&#10;&#10;Answer the call of the ruins and begin your journey.&#10;&#10;Errata&#10;&#10;",
    yearPublished: 2017,
    minPlayers: 2,
    maxPlayers: 4,
    playTime: 120,
    minAge: 13,
  },
];

module.exports = {
  gamesData,
};
